/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cricket;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author GAUTHAM
 */
public class Window extends javax.swing.JFrame {

    private Connection connection;
    /**
     * Creates new form Window
     */
    public Window() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            connection=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","c##project","galloway");
        } catch (SQLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        viewPointsBtn = new javax.swing.JButton();
        viewPlayersBtn = new javax.swing.JButton();
        viewMatchesBtn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        pointsPanel = new javax.swing.JPanel();
        pointsHeadingLabel = new javax.swing.JLabel();
        pointsGoBackBtn = new javax.swing.JButton();
        pointsScrollPane = new javax.swing.JScrollPane();
        pointsTable = new javax.swing.JTable();
        addTeamBtn = new javax.swing.JButton();
        delTeamBtn = new javax.swing.JButton();
        updateTeamBtn = new javax.swing.JButton();
        playersPanel = new javax.swing.JPanel();
        playersHeadingLabel = new javax.swing.JLabel();
        playersGoBackBtn = new javax.swing.JButton();
        playersScrollPane = new javax.swing.JScrollPane();
        playersTable = new javax.swing.JTable();
        addPlayersBtn = new javax.swing.JButton();
        delPlayersBtn = new javax.swing.JButton();
        updatePlayersBtn = new javax.swing.JButton();
        matchesPanel = new javax.swing.JPanel();
        matchesHeadingLabel = new javax.swing.JLabel();
        matchesGoBackBtn = new javax.swing.JButton();
        matchesScrollPane = new javax.swing.JScrollPane();
        matchesTable = new javax.swing.JTable();
        addMatchBtn = new javax.swing.JButton();
        delMatchBtn = new javax.swing.JButton();
        updateMatchBtn = new javax.swing.JButton();
        addMatchPanel = new javax.swing.JPanel();
        addMatchHeadingLabel = new javax.swing.JLabel();
        addMatchGoBackBtn = new javax.swing.JButton();
        team1Label = new javax.swing.JLabel();
        team2Label = new javax.swing.JLabel();
        venueLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        tossWinnerLabel = new javax.swing.JLabel();
        tossDecisionLabel = new javax.swing.JLabel();
        innings1ScoreLabel = new javax.swing.JLabel();
        innings2ScoreLabel = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        winMarginLabel = new javax.swing.JLabel();
        addMatchSubmitBtn = new javax.swing.JButton();
        addMatchTeam1 = new javax.swing.JTextField();
        addMatchTeam2 = new javax.swing.JTextField();
        addMatchVenue = new javax.swing.JTextField();
        addMatchTossWinner = new javax.swing.JTextField();
        addMatchTossDecision = new javax.swing.JTextField();
        addMatchInnings1Score = new javax.swing.JTextField();
        addMatchInnings2Score = new javax.swing.JTextField();
        addMatchWinner = new javax.swing.JTextField();
        addMatchWinMargin = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        delMatchPanel = new javax.swing.JPanel();
        delMatchHeading = new javax.swing.JLabel();
        delMatchGoBackButton = new javax.swing.JButton();
        Team1Label = new javax.swing.JLabel();
        Team2Label = new javax.swing.JLabel();
        delMatchTeam1 = new javax.swing.JTextField();
        delMatchTeam2 = new javax.swing.JTextField();
        delMatchSubmitBtn = new javax.swing.JButton();
        updateMatchPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        addPlayerPanel = new javax.swing.JPanel();
        addPlayerHeadingLabel = new javax.swing.JLabel();
        addPlayerGoBackBtn = new javax.swing.JButton();
        addPlayerFirstNameLabel = new javax.swing.JLabel();
        addPlayerLastNameLabel = new javax.swing.JLabel();
        addPlayerTeamLabel = new javax.swing.JLabel();
        addPlayerDOBLabel = new javax.swing.JLabel();
        addPlayerBattingHandLabel = new javax.swing.JLabel();
        addPlayerBowlingSkillLabel = new javax.swing.JLabel();
        addPlayerCountryLabel = new javax.swing.JLabel();
        addPlayerJerseyLabel = new javax.swing.JLabel();
        addPlayerRunsScoredLabel = new javax.swing.JLabel();
        addPlayerWicketsTakenLabel = new javax.swing.JLabel();
        addPlayerSubmitBtn = new javax.swing.JButton();
        addPlayerFirstName = new javax.swing.JTextField();
        addPlayerLastName = new javax.swing.JTextField();
        addPlayerTeam = new javax.swing.JTextField();
        addPlayerBattingHand = new javax.swing.JTextField();
        addPlayerBowlingSkill = new javax.swing.JTextField();
        addPlayerCountry = new javax.swing.JTextField();
        addPlayerJerseyNumber = new javax.swing.JTextField();
        addPlayerRunsScored = new javax.swing.JTextField();
        addPlayerWicketsTaken = new javax.swing.JTextField();
        addPlayerDOBDay = new javax.swing.JComboBox<>();
        addPlayerDOBMonth = new javax.swing.JComboBox<>();
        addPlayerDOBYear = new javax.swing.JComboBox<>();
        delPlayerPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        updatePlayerPanel = new javax.swing.JPanel();
        addTeamPanel = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        delTeamPanel = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        updateTeamPanel = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        viewPointsBtn.setText("View points table");
        viewPointsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPointsBtnActionPerformed(evt);
            }
        });

        viewPlayersBtn.setText("View players");
        viewPlayersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPlayersBtnActionPerformed(evt);
            }
        });

        viewMatchesBtn.setText("View matches");
        viewMatchesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMatchesBtnActionPerformed(evt);
            }
        });

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome to Cricket Database!!!");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(viewPointsBtn)
                .addGap(18, 18, 18)
                .addComponent(viewPlayersBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewMatchesBtn)
                .addGap(51, 51, 51))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPointsBtn)
                    .addComponent(viewPlayersBtn)
                    .addComponent(viewMatchesBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "homePanel");

        pointsHeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointsHeadingLabel.setText("POINTS TABLE");

        pointsGoBackBtn.setText("Go back");
        pointsGoBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsGoBackBtnActionPerformed(evt);
            }
        });

        pointsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        pointsScrollPane.setViewportView(pointsTable);

        addTeamBtn.setText("Add team");
        addTeamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamBtnActionPerformed(evt);
            }
        });

        delTeamBtn.setText("Delete team");

        updateTeamBtn.setText("Update team");

        javax.swing.GroupLayout pointsPanelLayout = new javax.swing.GroupLayout(pointsPanel);
        pointsPanel.setLayout(pointsPanelLayout);
        pointsPanelLayout.setHorizontalGroup(
            pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsPanelLayout.createSequentialGroup()
                .addGroup(pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pointsPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(pointsGoBackBtn)
                        .addGap(34, 34, 34)
                        .addComponent(pointsHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pointsPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(addTeamBtn)
                        .addGap(40, 40, 40)
                        .addComponent(delTeamBtn)
                        .addGap(53, 53, 53)
                        .addComponent(updateTeamBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pointsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pointsPanelLayout.setVerticalGroup(
            pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsPanelLayout.createSequentialGroup()
                .addGroup(pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointsHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pointsGoBackBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pointsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTeamBtn)
                    .addComponent(delTeamBtn)
                    .addComponent(updateTeamBtn))
                .addGap(31, 31, 31))
        );

        mainPanel.add(pointsPanel, "pointsPanel");

        playersHeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playersHeadingLabel.setText("PLAYER DETAILS");

        playersGoBackBtn.setText("Go back");
        playersGoBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playersGoBackBtnActionPerformed(evt);
            }
        });

        playersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        playersScrollPane.setViewportView(playersTable);

        addPlayersBtn.setText("Add player");
        addPlayersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayersBtnActionPerformed(evt);
            }
        });

        delPlayersBtn.setText("Delete player");

        updatePlayersBtn.setText("Update player");

        javax.swing.GroupLayout playersPanelLayout = new javax.swing.GroupLayout(playersPanel);
        playersPanel.setLayout(playersPanelLayout);
        playersPanelLayout.setHorizontalGroup(
            playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playersPanelLayout.createSequentialGroup()
                .addGroup(playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playersPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(playersGoBackBtn)
                        .addGap(34, 34, 34)
                        .addComponent(playersHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(playersPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(addPlayersBtn)
                        .addGap(18, 18, 18)
                        .addComponent(delPlayersBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updatePlayersBtn)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addComponent(playersScrollPane)
        );
        playersPanelLayout.setVerticalGroup(
            playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playersPanelLayout.createSequentialGroup()
                .addGroup(playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playersHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playersGoBackBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(playersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayersBtn)
                    .addComponent(delPlayersBtn)
                    .addComponent(updatePlayersBtn))
                .addGap(31, 31, 31))
        );

        mainPanel.add(playersPanel, "playersPanel");

        matchesHeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        matchesHeadingLabel.setText("MATCH DETAILS");

        matchesGoBackBtn.setText("Go back");
        matchesGoBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchesGoBackBtnActionPerformed(evt);
            }
        });

        matchesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        matchesScrollPane.setViewportView(matchesTable);

        addMatchBtn.setText("Add match");
        addMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatchBtnActionPerformed(evt);
            }
        });

        delMatchBtn.setText("Delete match");
        delMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delMatchBtnActionPerformed(evt);
            }
        });

        updateMatchBtn.setText("Update match");

        javax.swing.GroupLayout matchesPanelLayout = new javax.swing.GroupLayout(matchesPanel);
        matchesPanel.setLayout(matchesPanelLayout);
        matchesPanelLayout.setHorizontalGroup(
            matchesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matchesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
            .addGroup(matchesPanelLayout.createSequentialGroup()
                .addGroup(matchesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(matchesPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(matchesGoBackBtn)
                        .addGap(34, 34, 34)
                        .addComponent(matchesHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(matchesPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(addMatchBtn)
                        .addGap(35, 35, 35)
                        .addComponent(delMatchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateMatchBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        matchesPanelLayout.setVerticalGroup(
            matchesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matchesPanelLayout.createSequentialGroup()
                .addGroup(matchesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchesHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matchesGoBackBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(matchesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(matchesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMatchBtn)
                    .addComponent(delMatchBtn)
                    .addComponent(updateMatchBtn))
                .addGap(31, 31, 31))
        );

        mainPanel.add(matchesPanel, "matchesPanel");

        addMatchHeadingLabel.setText("ADD MATCH");

        addMatchGoBackBtn.setText("Go back");

        team1Label.setText("Team 1");

        team2Label.setText("Team 2");

        venueLabel.setText("Venue");

        dateLabel.setText("Date");

        tossWinnerLabel.setText("Toss Winner");

        tossDecisionLabel.setText("Toss decision");

        innings1ScoreLabel.setText("Innings 1 score");

        innings2ScoreLabel.setText("Innings 2 score");

        winnerLabel.setText("Winner");

        winMarginLabel.setText("Win margin");

        addMatchSubmitBtn.setText("SUBMIT");
        addMatchSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatchSubmitBtnActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addMatchPanelLayout = new javax.swing.GroupLayout(addMatchPanel);
        addMatchPanel.setLayout(addMatchPanelLayout);
        addMatchPanelLayout.setHorizontalGroup(
            addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMatchPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addMatchSubmitBtn)
                    .addGroup(addMatchPanelLayout.createSequentialGroup()
                        .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addMatchGoBackBtn)
                            .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(team2Label)
                                .addComponent(team1Label)
                                .addComponent(venueLabel)
                                .addComponent(dateLabel)
                                .addComponent(tossWinnerLabel)
                                .addComponent(tossDecisionLabel)
                                .addComponent(innings1ScoreLabel)
                                .addComponent(innings2ScoreLabel)
                                .addComponent(winnerLabel)
                                .addComponent(winMarginLabel)))
                        .addGap(47, 47, 47)
                        .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addMatchHeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addMatchTeam1)
                            .addComponent(addMatchTeam2)
                            .addComponent(addMatchVenue)
                            .addComponent(addMatchTossWinner)
                            .addComponent(addMatchTossDecision)
                            .addComponent(addMatchInnings1Score)
                            .addComponent(addMatchInnings2Score)
                            .addComponent(addMatchWinner)
                            .addComponent(addMatchWinMargin)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMatchPanelLayout.setVerticalGroup(
            addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMatchPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMatchHeadingLabel)
                    .addComponent(addMatchGoBackBtn))
                .addGap(25, 25, 25)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(team1Label)
                    .addComponent(addMatchTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(team2Label)
                    .addComponent(addMatchTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venueLabel)
                    .addComponent(addMatchVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tossWinnerLabel)
                    .addComponent(addMatchTossWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tossDecisionLabel)
                    .addComponent(addMatchTossDecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(innings1ScoreLabel)
                    .addComponent(addMatchInnings1Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(innings2ScoreLabel)
                    .addComponent(addMatchInnings2Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winnerLabel)
                    .addComponent(addMatchWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winMarginLabel)
                    .addComponent(addMatchWinMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(addMatchSubmitBtn)
                .addContainerGap())
        );

        mainPanel.add(addMatchPanel, "addMatchPanel");

        delMatchHeading.setText("DELETE MATCH");

        delMatchGoBackButton.setText("Go back");

        Team1Label.setText("Enter team 1");

        Team2Label.setText("Enter team 2");

        delMatchSubmitBtn.setText("SUBMIT");
        delMatchSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delMatchSubmitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delMatchPanelLayout = new javax.swing.GroupLayout(delMatchPanel);
        delMatchPanel.setLayout(delMatchPanelLayout);
        delMatchPanelLayout.setHorizontalGroup(
            delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delMatchPanelLayout.createSequentialGroup()
                .addGroup(delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delMatchPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(delMatchGoBackButton))
                    .addGroup(delMatchPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Team2Label)
                            .addComponent(Team1Label))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delMatchSubmitBtn)
                    .addComponent(delMatchHeading)
                    .addGroup(delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(delMatchTeam2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addComponent(delMatchTeam1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(153, 153, 153))
        );
        delMatchPanelLayout.setVerticalGroup(
            delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delMatchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delMatchHeading)
                    .addComponent(delMatchGoBackButton))
                .addGap(34, 34, 34)
                .addGroup(delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Team1Label)
                    .addComponent(delMatchTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(delMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team2Label)
                    .addComponent(delMatchTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(delMatchSubmitBtn)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        mainPanel.add(delMatchPanel, "delMatchPanel");

        jLabel26.setText("UPDATE MATCH DETAILS");

        jButton7.setText("Go back");

        jLabel27.setText("Enter team 1");

        jLabel28.setText("Enter team 2");

        jLabel29.setText("Choose field to edit");

        jLabel30.setText("Changes");

        jButton8.setText("SUBMIT");

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout updateMatchPanelLayout = new javax.swing.GroupLayout(updateMatchPanel);
        updateMatchPanel.setLayout(updateMatchPanelLayout);
        updateMatchPanelLayout.setHorizontalGroup(
            updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateMatchPanelLayout.createSequentialGroup()
                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateMatchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel26))
                    .addGroup(updateMatchPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateMatchPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updateMatchPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateMatchPanelLayout.createSequentialGroup()
                                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(updateMatchPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton8)))
                .addGap(86, 86, 86))
        );
        updateMatchPanelLayout.setVerticalGroup(
            updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateMatchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jButton7))
                .addGap(34, 34, 34)
                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateMatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton8)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        mainPanel.add(updateMatchPanel, "updateMatchPanel");

        addPlayerHeadingLabel.setText("ADD PLAYER");

        addPlayerGoBackBtn.setText("Go back");

        addPlayerFirstNameLabel.setText("First name");

        addPlayerLastNameLabel.setText("Last name");

        addPlayerTeamLabel.setText("Team");

        addPlayerDOBLabel.setText("Date of birth");

        addPlayerBattingHandLabel.setText("Batting hand");

        addPlayerBowlingSkillLabel.setText("Bowling skill");

        addPlayerCountryLabel.setText("Country");

        addPlayerJerseyLabel.setText("Jersey number");

        addPlayerRunsScoredLabel.setText("Runs scored");

        addPlayerWicketsTakenLabel.setText("Wickets taken");

        addPlayerSubmitBtn.setText("SUBMIT");
        addPlayerSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerSubmitBtnActionPerformed(evt);
            }
        });

        addPlayerFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerFirstNameActionPerformed(evt);
            }
        });

        addPlayerJerseyNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerJerseyNumberActionPerformed(evt);
            }
        });

        addPlayerDOBDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        addPlayerDOBDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerDOBDayActionPerformed(evt);
            }
        });

        addPlayerDOBMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        addPlayerDOBYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970" }));

        javax.swing.GroupLayout addPlayerPanelLayout = new javax.swing.GroupLayout(addPlayerPanel);
        addPlayerPanel.setLayout(addPlayerPanelLayout);
        addPlayerPanelLayout.setHorizontalGroup(
            addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPlayerPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addPlayerSubmitBtn)
                    .addGroup(addPlayerPanelLayout.createSequentialGroup()
                        .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addPlayerGoBackBtn)
                            .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addPlayerLastNameLabel)
                                .addComponent(addPlayerFirstNameLabel)
                                .addComponent(addPlayerTeamLabel)
                                .addComponent(addPlayerDOBLabel)
                                .addComponent(addPlayerBattingHandLabel)
                                .addComponent(addPlayerBowlingSkillLabel)
                                .addComponent(addPlayerCountryLabel)
                                .addComponent(addPlayerJerseyLabel)
                                .addComponent(addPlayerRunsScoredLabel)
                                .addComponent(addPlayerWicketsTakenLabel)))
                        .addGap(47, 47, 47)
                        .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addPlayerHeadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPlayerFirstName)
                            .addComponent(addPlayerLastName)
                            .addComponent(addPlayerTeam)
                            .addComponent(addPlayerBattingHand)
                            .addComponent(addPlayerBowlingSkill)
                            .addComponent(addPlayerCountry)
                            .addComponent(addPlayerJerseyNumber)
                            .addComponent(addPlayerRunsScored)
                            .addComponent(addPlayerWicketsTaken)
                            .addComponent(addPlayerDOBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(addPlayerDOBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPlayerDOBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPlayerPanelLayout.setVerticalGroup(
            addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPlayerPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerHeadingLabel)
                    .addComponent(addPlayerGoBackBtn))
                .addGap(25, 25, 25)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerFirstNameLabel)
                    .addComponent(addPlayerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerLastNameLabel)
                    .addComponent(addPlayerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerTeamLabel)
                    .addComponent(addPlayerTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerDOBLabel)
                    .addComponent(addPlayerDOBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPlayerDOBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPlayerDOBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerBattingHandLabel)
                    .addComponent(addPlayerBattingHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerBowlingSkillLabel)
                    .addComponent(addPlayerBowlingSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerCountryLabel)
                    .addComponent(addPlayerCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerJerseyLabel)
                    .addComponent(addPlayerJerseyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerRunsScoredLabel)
                    .addComponent(addPlayerRunsScored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerWicketsTakenLabel)
                    .addComponent(addPlayerWicketsTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPlayerSubmitBtn)
                .addContainerGap())
        );

        mainPanel.add(addPlayerPanel, "addPlayerPanel");

        jLabel31.setText("DELETE PLAYER");

        jButton9.setText("Go back");

        jLabel32.setText("Enter first name");

        jLabel33.setText("Enter last name");

        jButton10.setText("SUBMIT");

        javax.swing.GroupLayout delPlayerPanelLayout = new javax.swing.GroupLayout(delPlayerPanel);
        delPlayerPanel.setLayout(delPlayerPanelLayout);
        delPlayerPanelLayout.setHorizontalGroup(
            delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delPlayerPanelLayout.createSequentialGroup()
                .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delPlayerPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton9))
                    .addGroup(delPlayerPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32))))
                .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delPlayerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jLabel31))
                        .addGap(153, 153, 153))
                    .addGroup(delPlayerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        delPlayerPanelLayout.setVerticalGroup(
            delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delPlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jButton9))
                .addGap(31, 31, 31)
                .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(delPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton10)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        mainPanel.add(delPlayerPanel, "delPlayerPanel");

        javax.swing.GroupLayout updatePlayerPanelLayout = new javax.swing.GroupLayout(updatePlayerPanel);
        updatePlayerPanel.setLayout(updatePlayerPanelLayout);
        updatePlayerPanelLayout.setHorizontalGroup(
            updatePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        updatePlayerPanelLayout.setVerticalGroup(
            updatePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        mainPanel.add(updatePlayerPanel, "updatePlayerPanel");

        jLabel34.setText("ADD TEAM");

        jButton11.setText("Go back");

        jLabel35.setText("Name");

        jLabel36.setText("Captain");

        jLabel37.setText("Coach");

        jLabel38.setText("Played");

        jLabel39.setText("Wins");

        jLabel40.setText("Loss");

        jLabel41.setText("Tied");

        jLabel42.setText("Points");

        jButton12.setText("SUBMIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });

        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTeamPanelLayout = new javax.swing.GroupLayout(addTeamPanel);
        addTeamPanel.setLayout(addTeamPanelLayout);
        addTeamPanelLayout.setHorizontalGroup(
            addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTeamPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11)
                    .addGroup(addTeamPanelLayout.createSequentialGroup()
                        .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addGap(36, 36, 36)))
                .addGap(47, 47, 47)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(jTextField26)
                        .addComponent(jTextField27)
                        .addComponent(jTextField28)
                        .addComponent(jTextField29)
                        .addComponent(jTextField30)
                        .addComponent(jTextField31)
                        .addComponent(jTextField32)
                        .addComponent(jTextField33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addTeamPanelLayout.setVerticalGroup(
            addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTeamPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jButton11))
                .addGap(25, 25, 25)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(addTeamPanel, "addTeamPanel");

        jLabel43.setText("DELETE TEAM");

        jButton13.setText("Go back");

        jLabel44.setText("Enter team");

        jButton14.setText("SUBMIT");

        javax.swing.GroupLayout delTeamPanelLayout = new javax.swing.GroupLayout(delTeamPanel);
        delTeamPanel.setLayout(delTeamPanelLayout);
        delTeamPanelLayout.setHorizontalGroup(
            delTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delTeamPanelLayout.createSequentialGroup()
                .addGroup(delTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(delTeamPanelLayout.createSequentialGroup()
                        .addGroup(delTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(delTeamPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton13))
                            .addGroup(delTeamPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(delTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(delTeamPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton14)
                        .addGap(10, 10, 10)))
                .addGap(153, 153, 153))
        );
        delTeamPanelLayout.setVerticalGroup(
            delTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delTeamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jButton13))
                .addGap(34, 34, 34)
                .addGroup(delTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton14)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        mainPanel.add(delTeamPanel, "delTeamPanel");

        jLabel45.setText("UPDATE TEAM DETAILS");

        jButton15.setText("Go back");

        jLabel46.setText("Enter team");

        jLabel47.setText("Choose field to edit");

        jLabel48.setText("Changes");

        jButton16.setText("SUBMIT");

        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });

        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout updateTeamPanelLayout = new javax.swing.GroupLayout(updateTeamPanel);
        updateTeamPanel.setLayout(updateTeamPanelLayout);
        updateTeamPanelLayout.setHorizontalGroup(
            updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateTeamPanelLayout.createSequentialGroup()
                .addGroup(updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateTeamPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton15)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel45))
                    .addGroup(updateTeamPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addGroup(updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
            .addGroup(updateTeamPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateTeamPanelLayout.setVerticalGroup(
            updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateTeamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jButton15))
                .addGap(34, 34, 34)
                .addGroup(updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButton16)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        mainPanel.add(updateTeamPanel, "updateTeamPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewPointsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPointsBtnActionPerformed
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        pointsTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Name");
        defaultTableModel.addColumn("Captain");
        defaultTableModel.addColumn("Coach");
        defaultTableModel.addColumn("Played");
        defaultTableModel.addColumn("Won");
        defaultTableModel.addColumn("Lost");
        defaultTableModel.addColumn("Tied");
        defaultTableModel.addColumn("Points");
        
        try {
            Statement statement = connection.createStatement();//crating statement object
            String query = "SELECT a.name, b.fname, b.lname, a.coach, a.played, a.wins, a.loss, a.tied, a.points from team a, player b WHERE a.captain=b.player_id ORDER BY a.points desc";
            ResultSet resultSet = statement.executeQuery(query);//executing query and storing result in ResultSet

            while (resultSet.next()) {
                //Retrieving details from the database and storing it in the String variables
                String name = resultSet.getString(1);
                String captain = resultSet.getString(2) + " " + resultSet.getString(3);
                String coach = resultSet.getString(4);
                int played = resultSet.getInt(5);
                int wins = resultSet.getInt(6);
                int loss = resultSet.getInt(7);
                int tied = resultSet.getInt(8);
                int points = resultSet.getInt(9);
                defaultTableModel.addRow(new Object[]{name, captain, coach, played, wins, loss, tied, points});
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "pointsPanel");
    }//GEN-LAST:event_viewPointsBtnActionPerformed

    private void viewPlayersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPlayersBtnActionPerformed
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        playersTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Name");
        defaultTableModel.addColumn("Team");
        defaultTableModel.addColumn("DOB");
        defaultTableModel.addColumn("Batting Hand");
        defaultTableModel.addColumn("Bowling Skill");
        defaultTableModel.addColumn("Country");
        defaultTableModel.addColumn("Jersey N.o");
        defaultTableModel.addColumn("Runs");
        defaultTableModel.addColumn("Wickets");

        try {
            Statement statement = connection.createStatement();//crating statement object
            String query = "SELECT a.fname, a.lname, b.name, a.dob, a.batting_hand, a.bowling_skill, a.country, a.jersey_no, a.runs, a.wickets from player a, team b where a.team_id=b.team_id";
            ResultSet resultSet = statement.executeQuery(query);//executing query and storing result in ResultSet

            while (resultSet.next()) {
                //Retrieving details from the database and storing it in the String variables
                String name = resultSet.getString(1) + " " + resultSet.getString(2);
                String team = resultSet.getString(3);
                String dob = resultSet.getString(4);
                String battingHand = resultSet.getString(5);
                String bowlingSkill = resultSet.getString(6);
                String country = resultSet.getString(7);
                int jerseyNo = resultSet.getInt(8);
                int runs = resultSet.getInt(9);
                int wickets =resultSet.getInt(10);
                defaultTableModel.addRow(new Object[]{name, team, dob, battingHand, bowlingSkill, country, jerseyNo, runs, wickets});
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "playersPanel");
    }//GEN-LAST:event_viewPlayersBtnActionPerformed

    private void viewMatchesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMatchesBtnActionPerformed
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        matchesTable.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Team 1");
        defaultTableModel.addColumn("Team 2");
        defaultTableModel.addColumn("Match Date");
        defaultTableModel.addColumn("Venue");
        defaultTableModel.addColumn("Toss Winner");
        defaultTableModel.addColumn("Toss Decision");
        defaultTableModel.addColumn("Innings 1");
        defaultTableModel.addColumn("Innings 2");
        defaultTableModel.addColumn("Winner");
        defaultTableModel.addColumn("Win Margin");
        try {
            Statement statement = connection.createStatement();//crating statement object
            String query = "SELECT a.name, b.name, c.match_date, c.venue, d.name, c.toss_decision, c.innings_1_score, c.innings_2_score, e.name, c.win_margin from team a, team b, match c, team d, team e where a.team_id=c.team_1 and b.team_id=c.team_2 and d.team_id=c.toss_winner and e.team_id=c.winner";
            ResultSet resultSet = statement.executeQuery(query);//executing query and storing result in ResultSet

            while (resultSet.next()) {
                //Retrieving details from the database and storing it in the String variables
                String team1 = resultSet.getString(1);
                String team2 = resultSet.getString(2);
                String matchDate = resultSet.getString(3);
                String venue = resultSet.getString(4);
                String tossWinner = resultSet.getString(5);
                String tossDecision = resultSet.getString(6);
                String innings1Score = resultSet.getString(7);
                String innings2Score = resultSet.getString(8);
                String winner = resultSet.getString(9);
                String winMargin = resultSet.getString(10);
                defaultTableModel.addRow(new Object[]{team1, team2, matchDate, venue, tossWinner, tossDecision, innings1Score, innings2Score, winner, winMargin});
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "matchesPanel");
    }//GEN-LAST:event_viewMatchesBtnActionPerformed

    private void pointsGoBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsGoBackBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_pointsGoBackBtnActionPerformed

    private void playersGoBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playersGoBackBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
        
    }//GEN-LAST:event_playersGoBackBtnActionPerformed

    private void matchesGoBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchesGoBackBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_matchesGoBackBtnActionPerformed

    private void addMatchSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatchSubmitBtnActionPerformed
        viewMatchesBtnActionPerformed(evt);
    }//GEN-LAST:event_addMatchSubmitBtnActionPerformed

    private void addPlayerSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerSubmitBtnActionPerformed
        String fName = addPlayerFirstName.getText().toUpperCase();
        String lName = addPlayerLastName.getText().toUpperCase();
        String teamID = addPlayerTeam.getText().toUpperCase();
        String day = addPlayerDOBDay.getSelectedItem().toString().toUpperCase();
        String month = addPlayerDOBMonth.getSelectedItem().toString().toUpperCase();
        String year = addPlayerDOBYear.getSelectedItem().toString().toUpperCase();
        String battingHand = addPlayerBattingHand.getText().toUpperCase();
        String bowlingSkill = addPlayerBowlingSkill.getText().toUpperCase();
        String country = addPlayerCountry.getText().toUpperCase();
        String jerseyNo = addPlayerJerseyNumber.getText().toUpperCase();
        String runs = addPlayerRunsScored.getText().toUpperCase();
        String wickets = addPlayerWicketsTaken.getText().toUpperCase();
        
        String date = String.join("-", day, month, year);
        String query = "INSERT INTO player (FNAME,LNAME,DOB,BATTING_HAND,BOWLING_SKILL,COUNTRY,JERSEY_NO,RUNS,WICKETS,TEAM_ID)"+
                "VALUES('" + String.join("','", fName, lName, date, battingHand, bowlingSkill, country) + "'," + String.join(",", jerseyNo, runs, wickets, teamID) + ")";
        Statement stmt;
        System.out.println(query);
        try {
            stmt = connection.createStatement();
            stmt.execute(query);
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "playersPanel");
        } catch (SQLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addPlayerSubmitBtnActionPerformed

    private void addPlayerFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPlayerFirstNameActionPerformed

    private void addPlayerJerseyNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerJerseyNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPlayerJerseyNumberActionPerformed

    private void addPlayerDOBDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerDOBDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPlayerDOBDayActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void addTeamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addTeamPanel");
    }//GEN-LAST:event_addTeamBtnActionPerformed

    private void addMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatchBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addMatchPanel");
    }//GEN-LAST:event_addMatchBtnActionPerformed

    private void delMatchSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delMatchSubmitBtnActionPerformed
        viewMatchesBtnActionPerformed(evt);
    }//GEN-LAST:event_delMatchSubmitBtnActionPerformed

    private void delMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delMatchBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "delMatchPanel");
    }//GEN-LAST:event_delMatchBtnActionPerformed

    private void addPlayersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayersBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addPlayerPanel");
    }//GEN-LAST:event_addPlayersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Team1Label;
    private javax.swing.JLabel Team2Label;
    private javax.swing.JButton addMatchBtn;
    private javax.swing.JButton addMatchGoBackBtn;
    private javax.swing.JLabel addMatchHeadingLabel;
    private javax.swing.JTextField addMatchInnings1Score;
    private javax.swing.JTextField addMatchInnings2Score;
    private javax.swing.JPanel addMatchPanel;
    private javax.swing.JButton addMatchSubmitBtn;
    private javax.swing.JTextField addMatchTeam1;
    private javax.swing.JTextField addMatchTeam2;
    private javax.swing.JTextField addMatchTossDecision;
    private javax.swing.JTextField addMatchTossWinner;
    private javax.swing.JTextField addMatchVenue;
    private javax.swing.JTextField addMatchWinMargin;
    private javax.swing.JTextField addMatchWinner;
    private javax.swing.JTextField addPlayerBattingHand;
    private javax.swing.JLabel addPlayerBattingHandLabel;
    private javax.swing.JTextField addPlayerBowlingSkill;
    private javax.swing.JLabel addPlayerBowlingSkillLabel;
    private javax.swing.JTextField addPlayerCountry;
    private javax.swing.JLabel addPlayerCountryLabel;
    private javax.swing.JComboBox<String> addPlayerDOBDay;
    private javax.swing.JLabel addPlayerDOBLabel;
    private javax.swing.JComboBox<String> addPlayerDOBMonth;
    private javax.swing.JComboBox<String> addPlayerDOBYear;
    private javax.swing.JTextField addPlayerFirstName;
    private javax.swing.JLabel addPlayerFirstNameLabel;
    private javax.swing.JButton addPlayerGoBackBtn;
    private javax.swing.JLabel addPlayerHeadingLabel;
    private javax.swing.JLabel addPlayerJerseyLabel;
    private javax.swing.JTextField addPlayerJerseyNumber;
    private javax.swing.JTextField addPlayerLastName;
    private javax.swing.JLabel addPlayerLastNameLabel;
    private javax.swing.JPanel addPlayerPanel;
    private javax.swing.JTextField addPlayerRunsScored;
    private javax.swing.JLabel addPlayerRunsScoredLabel;
    private javax.swing.JButton addPlayerSubmitBtn;
    private javax.swing.JTextField addPlayerTeam;
    private javax.swing.JLabel addPlayerTeamLabel;
    private javax.swing.JTextField addPlayerWicketsTaken;
    private javax.swing.JLabel addPlayerWicketsTakenLabel;
    private javax.swing.JButton addPlayersBtn;
    private javax.swing.JButton addTeamBtn;
    private javax.swing.JPanel addTeamPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton delMatchBtn;
    private javax.swing.JButton delMatchGoBackButton;
    private javax.swing.JLabel delMatchHeading;
    private javax.swing.JPanel delMatchPanel;
    private javax.swing.JButton delMatchSubmitBtn;
    private javax.swing.JTextField delMatchTeam1;
    private javax.swing.JTextField delMatchTeam2;
    private javax.swing.JPanel delPlayerPanel;
    private javax.swing.JButton delPlayersBtn;
    private javax.swing.JButton delTeamBtn;
    private javax.swing.JPanel delTeamPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel innings1ScoreLabel;
    private javax.swing.JLabel innings2ScoreLabel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton matchesGoBackBtn;
    private javax.swing.JLabel matchesHeadingLabel;
    private javax.swing.JPanel matchesPanel;
    private javax.swing.JScrollPane matchesScrollPane;
    private javax.swing.JTable matchesTable;
    private javax.swing.JButton playersGoBackBtn;
    private javax.swing.JLabel playersHeadingLabel;
    private javax.swing.JPanel playersPanel;
    private javax.swing.JScrollPane playersScrollPane;
    private javax.swing.JTable playersTable;
    private javax.swing.JButton pointsGoBackBtn;
    private javax.swing.JLabel pointsHeadingLabel;
    private javax.swing.JPanel pointsPanel;
    private javax.swing.JScrollPane pointsScrollPane;
    private javax.swing.JTable pointsTable;
    private javax.swing.JLabel team1Label;
    private javax.swing.JLabel team2Label;
    private javax.swing.JLabel tossDecisionLabel;
    private javax.swing.JLabel tossWinnerLabel;
    private javax.swing.JButton updateMatchBtn;
    private javax.swing.JPanel updateMatchPanel;
    private javax.swing.JPanel updatePlayerPanel;
    private javax.swing.JButton updatePlayersBtn;
    private javax.swing.JButton updateTeamBtn;
    private javax.swing.JPanel updateTeamPanel;
    private javax.swing.JLabel venueLabel;
    private javax.swing.JButton viewMatchesBtn;
    private javax.swing.JButton viewPlayersBtn;
    private javax.swing.JButton viewPointsBtn;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel winMarginLabel;
    private javax.swing.JLabel winnerLabel;
    // End of variables declaration//GEN-END:variables
}
